GET http://localhost:9999/api/users?sort=name,-email&limit=asdasd


POST http://localhost:9000/api/users
Content-Type: application/json

{
    "name": "456",
    "email": "abc@xyz.com",
    "birthday": "abc"
}